-- Create Table

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  phone VARCHAR(20) NOT NULL,
  password VARCHAR(256) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'member',
  last_password VARCHAR(256),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE team (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE requester (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ticket (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  requester INT NOT NULL,
  team INT,
  team_member INT, 
  status ENUM('open', 'in_progress', 'resolved', 'closed') DEFAULT 'open',
  priority ENUM('low', 'medium', 'high') DEFAULT 'medium',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL
);

CREATE TABLE comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ticket INT NOT NULL,
  user_id INT NOT NULL,
  comment_text TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE team_member (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user INT NOT NULL,
  team INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

--Alter DDL

ALTER TABLE ticket
  ADD CONSTRAINT fk_ticket_requester
  FOREIGN KEY (requester)
  REFERENCES requester(id)
  ON DELETE SET NULL;

ALTER TABLE ticket
  ADD CONSTRAINT fk_ticket_team
  FOREIGN KEY (team)
  REFERENCES team(id)
  ON DELETE SET NULL;

ALTER TABLE comments
  ADD CONSTRAINT fk_comments_ticket
  FOREIGN KEY (ticket)
  REFERENCES ticket(id)
  ON DELETE CASCADE;

ALTER TABLE comments
  ADD CONSTRAINT fk_comments_team_member
  FOREIGN KEY (team_member)
  REFERENCES team_member(id)
  ON DELETE SET NULL;

ALTER TABLE team_member
  ADD CONSTRAINT fk_team_member_user
  FOREIGN KEY (user)
  REFERENCES requester(id)
  ON DELETE CASCADE;

ALTER TABLE team_member
  ADD CONSTRAINT fk_team_member_team
  FOREIGN KEY (team)
  REFERENCES team(id)
  ON DELETE CASCADE;

ALTER TABLE comments
  ADD CONSTRAINT fk_comments_user
  FOREIGN KEY (user_id)
  REFERENCES users(id)
  ON DELETE SET NULL;
